### PR TITLE
docs: fix copying code in safari

### LINKED ISSUE #4019: docs: Code `copy` not working
### Area of Improvement

The copy button for this page is not working

### Link to related docs

https://trpc.io/docs/ssg-helpers

### Additional information

_No response_

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing the suggested changes!

### PR DESCRIPTION
**Pull request by sachinraja**
Closes #4019

## 🎯 Changes

Use the [Clipboard API](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard) instead of `copy-text-to-clipboard`. Unfortunately this means we have to eject from twoslash's `CodeBlock` component ([which hasn't been updated in two years anyway](https://github.com/shikijs/twoslash/blob/f3a2683d1bd7fe64f424a808dcbdbc77b686c896/packages/docusaurus-preset-shiki-twoslash/docusaurus-theme-shiki-twoslash/theme/CodeBlock/index.js#L10)).

### CODE REVIEW

**Review by juliusmarminge — DISMISSED** [review]
Works!!

File: www/src/theme/CodeBlock/index.js [hunk 1]
```diff
@@ -0,0 +1,57 @@
...
+import Translate, { translate } from '@docusaurus/Translate';
+import React, { useRef, useState } from 'react';
+
+const CodeBlock = ({ children, ...props }) => {
+  const pre = useRef(null);
+  const [showCopied, setShowCopied] = useState(false);
+
+  const handleCopyCode = () => {
+    if (pre.current) {
+      navigator.clipboard.writeText(
```
Comment (juliusmarminge) [inline www/src/theme/CodeBlock/index.js:14]:
```suggestion
      void navigator.clipboard.writeText(
```

**Review by juliusmarminge — APPROVED** [review]
