### PR TITLE
patch: typescript 5.9 support

### LINKED ISSUE #6875: bug: httpBatchLink with credentials (CORS) throws a type-error on TypeScript 5.9.x
### Provide environment information

The script does not seem to catch the trpc/tanstack versions in my monorepo, added blow
  System:
    OS: Linux 6.16 CachyOS Linux
    CPU: (24) x64 12th Gen Intel(R) Core(TM) i9-12900K
    Memory: 55.49 GB / 62.51 GB
    Container: Yes
    Shell: 4.0.2 - /bin/fish
  Binaries:
    Node: 24.4.1 - ~/.nvm/versions/node/v24.4.1/bin/node
    Yarn: 4.9.2 - ~/.nvm/versions/node/v24.4.1/bin/yarn
    npm: 11.5.1 - ~/.nvm/versions/node/v24.4.1/bin/npm
  npmPackages:
    typescript: ^5.9.2 => 5.9.2 

react: 19.1.1, @trpc/x 11.4.3, @tanstack/react-query 5.84.0

### Describe the bug

Not sure if this is a trpc issue or a typescript bug, but might warrant investigating.

When setting up the httpBatchLink for CORS according to this guide https://trpc.io/docs/client/cors, typescript 5.9.x throws a type-error:

> src/App.tsx:12:27 - error TS2345: Argument of type '{ credentials: "include"; } | { credentials: "include"; body?: BodyInit | null | undefined; cache?: RequestCache | undefined; headers?: HeadersInit | undefined; ... 9 more ...; window?: null | undefined; } | { ...; }' is not assignable to parameter of type 'RequestInit | undefined'.
>   Type '{ credentials: "include"; body?: FormData | string | null | Uint8Array | Blob | File; headers?: [string, string][] | Record<string, string>; method?: string; signal?: AbortSignal | undefined; }' is not assignable to type 'RequestInit'.
>     Types of property 'body' are incompatible.
>       Type 'string | Blob | FormData | Uint8Array<ArrayBufferLike> | File | null | undefined' is not assignable to type 'BodyInit | null | undefined'.
>         Type 'Uint8Array<ArrayBufferLike>' is not assignable to type 'BodyInit | null | undefined'.
>           Type 'Uint8Array<ArrayBufferLike>' is missing the following properties from type 'URLSearchParams': size, append, delete, get, and 2 more.
> 
> 12         return fetch(url, {
>                              ~
> 13           ...options,
>    ~~~~~~~~~~~~~~~~~~~~~
> 14           credentials: 'include',
>    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 15         });
> 

### Link to reproduction

https://github.com/MarcSustainableShift/trpc

### To reproduce

The Reproduction Repo is just a clean vite react-ts template with the trpc-client library and typescript 5.9.2 installed. All other dependencies are updated to latest.

To reproduce, clone the repo, yarn install & yarn build.

The type error is only thrown on TypeScript 5.9.x. Downgrading to 5.8.x or using tsgo fixes the issue.

### Additional information

The Type Error is also thrown when cloning the trpc repo, updating typescript to 5.9.2, and running "tsc --noEmit" in the client package. 

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

### PR DESCRIPTION
**Pull request by KATT**
Closes #6875

## 🎯 Changes

Adds support for typescript 5.9

## ✅ Checklist

- [ ] I have followed the steps listed in the [Contributing guide](https://github.com/trpc/trpc/blob/main/CONTRIBUTING.md).
- [ ] If necessary, I have added documentation related to the changes made.
- [ ] I have added or updated the tests related to the changes made.

## Summary by CodeRabbit

* **Chores**
  * Updated the TypeScript dependency version from ^5.8.2 to ^5.9.2 across all example projects and packages.
  * Renamed and consolidated type-checking scripts for consistency across packages.
  * Added a dedicated type-checking job to the GitHub Actions workflow for pull requests.
  * Simplified test commands and updated testing instructions for watch mode.
  * Enhanced test setup to suppress specific React warnings for cleaner test output.
* **Bug Fixes**
  * Adjusted type definitions to support broader binary data formats in request bodies.
  * Improved type safety with enhanced type predicates for content type checks.

### CODE REVIEW

File: packages/client/src/internals/types.ts [hunk 1]
```diff
@@ -34,7 +34,7 @@ export interface RequestInitEsque {
   /**
    * Sets the request's body.
    */
-  body?: FormData | string | null | Uint8Array | Blob | File;
+  body?: FormData | string | null | Uint8Array<ArrayBuffer> | Blob | File;
```
Comment (KATT) [inline packages/client/src/internals/types.ts:37]: this is the main fix
