### PR TITLE
Fix subtle PromiseLike errors with `ProxyPromiseGuard`

### LINKED ISSUE #2521: bug: v10 resolving to return of `createTRPCProxyClient` throws `client[procedureType] is not a function` (path = `"then"`)
### Provide environment information

```
  System:
    OS: macOS 12.5
    CPU: (8) arm64 Apple M1
    Memory: 74.78 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.5.0 - ~/.nvm/versions/node/v18.5.0/bin/node
    Yarn: 1.22.17 - ~/.yarn/bin/yarn
    npm: 8.12.1 - ~/.nvm/versions/node/v18.5.0/bin/npm
  Browsers:
    Chrome: 104.0.5112.101
    Chrome Canary: 107.0.5257.0
    Firefox Developer Edition: 104.0
    Safari: 15.6
  npmPackages:
    @trpc/client: 10.0.0-alpha.50 => 10.0.0-alpha.50 
    @trpc/server: 10.0.0-alpha.50 => 10.0.0-alpha.50 
```

### Describe the bug

```js
async function normalLookingFunction() {
    return createTRPCProxyClient(anything)
}

// Throws `client[procedureType] is not a function` (path = `"then"`)
normalLookingFunction().then(client => console.log(client))
```

### To reproduce

See above

### Additional information

I understand there's some reason behind switching to `[operation].(mutate|query)` ordering, but I'm not exactly sure how to address this kind of issue where the user might have a `then` operation.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

### PR DESCRIPTION
**Pull request by colelawrence**
Closes #2521

## 🎯 Changes

Add `ProxyPromiseGuard` type and defensive handling in TRPC Proxy Client.

## ✅ Checklist

- [ ] I have followed the steps listed in the [Contributing guide](https://github.com/trpc/trpc/blob/main/CONTRIBUTING.md).
- [ ] If necessary, I have added documentation related to the changes made.
- [ ] I have added or updated the tests related to the changes made.

### CODE REVIEW

File: packages/client/src/createTRPCClientProxy.ts [hunk 1]
```diff
@@ -93,11 +93,17 @@ const clientCallTypeMap: Record<
 export function createTRPCClientProxy<TRouter extends AnyRouter>(
   client: Client<TRouter>,
 ) {
-  const proxy = createProxy(({ path, args }) => {
+  const proxy = createProxy((path, args) => {
```
Comment (colelawrence) [inline packages/client/src/createTRPCClientProxy.ts:96]: Spread out args are more performant, as we aren't allocating a new object every time.

File: packages/client/src/createTRPCClientProxy.ts [hunk 2]
```diff
@@ -93,11 +93,17 @@ const clientCallTypeMap: Record<
...
-    const procedureType = clientCallTypeMap[clientCallType];
-
+    const clientCallType = pathCopy.pop()!;
+    const procedureType =
+      clientCallTypeMap[clientCallType as keyof DecorateProcedure<any, any>];
+    if (!procedureType) {
+      // pass it on if we're being treated like a promise or something else
+      throw new TypeError(
+        `Unexpected call to "${path.join('.')}()" on TRPC proxy client.`,
+      );
```
Comment (colelawrence) [inline packages/client/src/createTRPCClientProxy.ts:105]: Ask: Copy/error okay?

**Review by KATT — CHANGES_REQUESTED** [review]
We need a test otherwise I'll definitely break it in the future

File: packages/server/src/shared/createProxy/index.ts [hunk 3]
```diff
@@ -4,6 +4,20 @@ interface ProxyCallbackOptions {
...
+   * We prevent our procedures from accidentally being treated as a PromiseLike
+   * by always ensuring that "then" resolves to `undefined`.
+   *
+   * This prevents errors where a proxy client is used in a promise callback or
+   * in a `Promise.resolve(proxy)`.
+   *
+   * This does mean that `then` is a reserved word and cannot be used to
+   * name any of your procedures.
+   */
+  then: undefined;
```
Comment (juliusmarminge) [inline packages/server/src/shared/createProxy/index.ts:18]: Also add `catch` and `finally` in here?

File: packages/server/src/shared/createProxy/index.ts [hunk 4]
```diff
@@ -12,6 +26,11 @@ function createProxyInner(callback: ProxyCallback, ...path: string[]) {
     {
       get(_obj, name) {
         if (typeof name === 'string') {
+          if (name === 'then') {
```
Comment (juliusmarminge) [inline packages/server/src/shared/createProxy/index.ts:29]: And here

File: packages/server/src/shared/createProxy/index.ts (hunk 3 above)
Comment (colelawrence) [reply packages/server/src/shared/createProxy/index.ts:18]: I don't believe it's necessary. `catch` and `finally` aren't important because they aren't actually checked in a Promise test if `then` is `undefined`.
Check
```js
Promise.resolve({ get catch() { console.log("catch") }, get then() { console.log("then") }, get finally() { console.log("finally") } })
```

Comment (colelawrence) [reply packages/server/src/shared/createProxy/index.ts:18]: I don't believe it's necessary. `catch` and `finally` aren't important because they aren't actually checked in a Promise test if `then` is `undefined`.
Check
```js
Promise.resolve({ get catch() { console.log("catch") }, get then() { console.log("then") }, get finally() { console.log("finally") } })
```

Comment (juliusmarminge) [reply packages/server/src/shared/createProxy/index.ts:18]: Oh nvm then. Learning something new everyday 😃

**Review by KATT — CHANGES_REQUESTED** [review]
Needs a test case to assert that this works.

All tests are in https://github.com/trpc/trpc/tree/next/packages/server/test

**Review by KATT — APPROVED** [review]

**Comment by KATT** [comment]
cc @colelawrence  -- I cleaned this up to what I think is the minimum needed and added tests
