### PR TITLE
fix `setInfiniteData`

### LINKED ISSUE #2942: bug: `setInfiniteData` sets optimistic update to `input`
### Provide environment information

```
System:
    OS: macOS 12.5.1
    CPU: (8) arm64 Apple M1
    Memory: 162.39 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - ~/Documents/dev/node_modules/.bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
  Browsers:
    Brave Browser: 105.1.43.89
    Chrome: 105.0.5195.125
    Edge: 106.0.1370.37
    Firefox: 105.0.1
    Safari: 15.6.1
  npmPackages:
    @tanstack/react-query: ^4.8.0 => 4.10.3
    @trpc/client: 10.0.0-proxy-beta.15 => 10.0.0-proxy-beta.15
    @trpc/next: 10.0.0-proxy-beta.15 => 10.0.0-proxy-beta.15
    @trpc/react: 10.0.0-proxy-beta.15 => 10.0.0-proxy-beta.15
    @trpc/server: 10.0.0-proxy-beta.15 => 10.0.0-proxy-beta.15
    next: 12.3.1 => 12.3.1
    react: 18.2.0 => 18.2.0
    typescript: 4.7.4 => 4.7.4
```

### Describe the bug

When optimistically updating an infinite query using `.setInfiniteData(updater, input)`, The query data is optimistically updated to `input`, instead of the result of the updater.

### Link to reproduction

https://github.com/c-ehrlich/setinfinitedata

### To reproduce

Full code sample in the above repo, but here is the key part:
```ts
const queryClient = trpc.useContext();

const { data: posts } = trpc.example.getPaginated.useInfiniteQuery({
  foo: "bar",
});

const create = trpc.example.create.useMutation({
  onMutate: () => {
    queryClient.example.getPaginated.cancel();

    queryClient.example.getPaginated.setInfiniteData((data) => data, {
      foo: "bar",
    });
  },
  onSettled: () => queryClient.example.getPaginated.invalidate(),
});

function handleCreate() {
  create.mutate({ id: String(Math.random()) });
}
```
TypeScript suggests that everything is in the right place

### Additional information

https://user-images.githubusercontent.com/8353666/194729466-9d29d187-54c3-4b00-b283-ae0861d07e1c.mov

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

### PR DESCRIPTION
**Pull request by KATT**
Closes #2942

## 🎯 Changes

- Not done, only added failing test
- ~~Maybe @sachinraja or @TkDodo could help understanding what's going on~~ nvm, i think i fixed it
  - Extra context: one of the new tests in the repro (w/o input) works, the other one doesn't
  - Might be that we have some types that are lying
  - Can't find any docs for `setInfiniteQueryData` but there are some for [`setQueryData`](https://tanstack.com/query/v4/docs/reference/QueryClient#queryclientsetquerydata)

## ✅ Checklist

- [x] I have followed the steps listed in the [Contributing guide](https://github.com/trpc/trpc/blob/main/CONTRIBUTING.md).
- [x] If necessary, I have added documentation related to the changes made.
- [x] I have added or updated the tests related to the changes made.

### CODE REVIEW

**Comment by TkDodo** [comment]
> Can't find any docs for setInfiniteQueryData but there are some for [setQueryData](https://tanstack.com/query/v4/docs/reference/QueryClient#queryclientsetquerydata)

There are no docs for `setInfiniteQueryData` because it doesn't exist 😅 . To set infinite data, what you need to do is:

```
queryClient.setQueryData<InfiniteData<MyData>>(['my-infinite-query-key'], myInfiniteData)
```

File: packages/react/src/shared/proxy/utilsProxy.ts [hunk 1]
```diff
@@ -257,7 +255,7 @@ export function createReactQueryUtilsProxy<
         cancel: () => context.cancelQuery(queryKey, ...rest),
         setData: () => context.setQueryData(queryKey, updater, ...rest),
         setInfiniteData: () =>
-          context.setInfiniteQueryData(queryKey, input, ...rest),
+          context.setInfiniteQueryData(queryKey, updater, ...rest),
```
Comment (c-ehrlich) [inline packages/react/src/shared/proxy/utilsProxy.ts:258]: Looks good, thanks for the fast fix! :)

**Review by c-ehrlich — APPROVED** [review]

**Comment by KATT** [comment]
> > Can't find any docs for setInfiniteQueryData but there are some for [setQueryData](https://tanstack.com/query/v4/docs/reference/QueryClient#queryclientsetquerydata)
> 
> There are no docs for `setInfiniteQueryData` because it doesn't exist 😅 . To set infinite data, what you need to do is:
> 
> ```
> queryClient.setQueryData<InfiniteData<MyData>>(['my-infinite-query-key'], myInfiniteData)
> ```

Hahaha, I had forgotten it was something we've created ourselves 🤦
