### PR TITLE
css: remove smooth scroll

### LINKED ISSUE #4646: docs/bug: Scroll doesn't reset upon navigation
### Area of Improvement

To reproduce:

1. Visit https://trpc.io/docs/quickstart
2. Scroll down
3. Navigate to "Concepts"

After navigation, the scroll position remains the same as the previous page on Chrome and WebKit, while on Firefox, it works as expected and scrolls to the top of the page.

### Link to related docs

_No response_

### Additional information

_No response_

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing the suggested changes!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/4646">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/4646/pledge.svg?darkmode=1">
  Fund with Polar
</picture>
</a>

### PR DESCRIPTION
**Pull request by pindjur**
Closes #4646

## 🎯 Changes

Remove smooth scroll behaviour from custom css.

## ✅ Checklist

- [x] I have followed the steps listed in the [Contributing guide](https://github.com/trpc/trpc/blob/main/CONTRIBUTING.md).
- [ ] If necessary, I have added documentation related to the changes made.
- [ ] I have added or updated the tests related to the changes made.
 I did write e2e test when I was fixing this bug locally, but don't think its good idea to have real browser running in a ci/cd just for this one test,
<details>

<summary>code</summary>

````ts
import { expect, test } from "@playwright/test";

test("should scroll to top on first visit navigation", async ({ page }) => {
  await page.goto("http://localhost:3000/docs/quickstart");

  await page.evaluate(() => window.scrollTo({ top: 400 }));

  await page.waitForTimeout(500);

  const conceptsLink = page
    .getByLabel("Docs sidebar")
    .getByRole("link", { name: "Concepts" });

  await conceptsLink.click();

  await page.waitForURL("**/docs/concepts");

  await page.waitForTimeout(500);

  const scrollTop = await page.evaluate(
    () => document.documentElement.scrollTop
  );

  console.log({ scrollTop });

  // await expect(scrollTop).toBe(0);
});
````

</details>

### CODE REVIEW

**Comment by KATT** [comment]
Cool by me! Could you possibly add that when you tap the coding example GIF in the hero we do a manual scroll smooth down to the stackblitz embed? :)

**Comment by pindjur** [comment]
We don't show stackblitz on screens up to md breakpoint, so this works as before.

File: www/src/utils/handleSmoothScrollToSection.ts [hunk 1]
```diff
@@ -0,0 +1,24 @@
...
+    e.preventDefault();
+
+    const href = e.currentTarget.href;
+
+    const id = href.split('#')[1];
+
+    const section = document.getElementById(id);
+    section?.scrollIntoView({ behavior: 'smooth' });
+
+    window.history.pushState(null, '', href);
```
Comment (KATT) [inline www/src/utils/handleSmoothScrollToSection.ts:20]: NICE!!! 👏 👏

**Review by KATT — APPROVED** [review]
