### PR TITLE
fix(client+server): non-records inferred as records when serializing as json

### LINKED ISSUE #5075: Incorrect Zod inferred type on build after upgrade from 10.43.3 to 10.43.7
### Provide environment information

```
  System:
    OS: macOS 14.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 1.37 GB / 16.00 GB
    Shell: 3.6.0 - /usr/local/bin/fish
  Binaries:
    Node: 20.6.1 - /private/var/folders/m8/j52mkrz542x0_pbl9g1f1xj00000gn/T/xfs-ddc1bbbc/node
    Yarn: 4.0.0 - /private/var/folders/m8/j52mkrz542x0_pbl9g1f1xj00000gn/T/xfs-ddc1bbbc/yarn
    npm: 9.8.1 - ~/.local/share/nvm/v20.6.1/bin/npm
  Browsers:
    Chrome: 119.0.6045.159
    Safari: 17.1
  npmPackages:
    react: ^18.2.0 => 18.2.0 
    typescript: ^5.3.2 => 5.3.2 
```

### Describe the bug

After updating the dependencies:
```
    "@trpc/client": "^10.43.3",
    "@trpc/react-query": "^10.43.3",
    "@trpc/server": "^10.43.3",
```
to 
```
    "@trpc/client": "^10.43.7",
    "@trpc/react-query": "^10.43.7",
    "@trpc/server": "^10.43.7",
```
my build fails because the inferred types from Zod are not correctly exported from my TRPC server to the client app importing them from there.

example of one of our Zod objects used as output on our xx-subscription-api server for TRPC request
```ts
...
const zChange = z.object({
  status: z.tuple([z.literal('tmp').or(z.literal('active')), z.literal('active').or(z.literal('disabled'))]).optional(),
  validFrom: z.tuple([z.string().nullable(), z.string()]).optional(),
  validTo: z.tuple([z.string().nullable(), z.string().nullable()]).optional(),
  worker: z.tuple([zWorker.nullable(), zWorker.nullable()]).optional(),
  canceled: z.tuple([z.boolean(), z.boolean()]).optional(),
  startsAt: z.tuple([z.string().nullable(), z.string().nullable()]).optional(),
  endsAt: z.tuple([z.string().nullable(), z.string().nullable()]).optional(),
  frequency: z.tuple([zAnyFrequency.nullable(), zAnyFrequency]).optional(),
});

const zHistory = z.object({
  updated: z.string(),
  updater: zUpdater.nullable(),
  eventType: zEventType,
  reason: zReason.nullable(),
  changes: zChange,
});

export const zSubscriptionHistory = z.object({
  timezone: z.string(),
  history: z.array(zHistory),
});

export type Change = z.infer<typeof zChange>;
export type History = z.infer<typeof zHistory>;
...
```

our component consuming the data from the TRPC useQuery

```ts
<>
    {subscriptionHistory.history.map(({ changes, reason, updated, updater, eventType }, index, array) => (
      <SubscriptionHistoryChangeEvent
        key={`change.updated-${index}`}
        isLastEvent={index === array.length - 1}
        change={changes} // ERROR OCCURS HERE (!)
        reason={reason}
        updated={updated}
        updater={updater}
        eventType={eventType}
        timezone={subscriptionHistory.timezone}
      />
    ))}
</>
```
                
props of the SubscriptionHistoryChangeEvent component
 
```ts
import type { Change, History, HistoryUpdater } from 'xx-subscription-api';
                
type SubscriptionHistoryChangeEventProps = {
  change: Change;
  eventType: History['eventType'];
  isLastEvent: boolean;
  reason: History['reason'];
  timezone: string;
  updated: History['updated'];
  updater: History['updater'];
};
```

The Change type on build however is a mashed ambiguous type
```ts
'Record<"status" | "endsAt" | "frequency" | "startsAt" | "worker" | "validFrom" | "validTo" | "canceled", ["tmp" | "active", "active" | "disabled"] | [string | null, string] | ... 4 more ... | undefined>' is not assignable to type '{ status?: ["tmp" | "active", "active" | "disabled"] | undefined; validFrom?: [string | null, string] | undefined; validTo?: [string | null, string | null] | undefined; ... 4 more ...; frequency?: [...] | undefined; }'.
```

                
                

### Link to reproduction

''

### To reproduce

''

### Additional information

_No response_

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

### PR DESCRIPTION
**Pull request by jussisaurio**
Closes #5075

## 🎯 Changes

💀 

## ✅ Checklist

- [x] I have followed the steps listed in the [Contributing guide](https://github.com/trpc/trpc/blob/main/CONTRIBUTING.md).
- [ ] If necessary, I have added documentation related to the changes made.
- [x] I have added or updated the tests related to the changes made.

### CODE REVIEW

**Comment by jussisaurio** [comment]
Should we have some sort of kitchen sink test somewhere that tests a huge vomitous mass of different inference scenarios? Kind of unfortunate how much we are breaking userland rn with these :(

This current issue is part of a chain reaction from https://github.com/trpc/trpc/issues/4985

File: packages/server/src/shared/internal/serialize.ts [hunk 1]
```diff
@@ -18,6 +18,8 @@ type IsAny<T> = 0 extends T & 1 ? true : false;
 // support it as both a Primitive and a NonJsonPrimitive
 type JsonReturnable = JsonPrimitive | undefined;
 
+type IsRecord<T> = keyof WithoutIndexSignature<T> extends never ? true : false;
```
Comment (jussisaurio) [inline packages/server/src/shared/internal/serialize.ts:21]: I'll change this to have an object check as well. Even though no tests fail, this is still too broad

**Comment by jussisaurio** [comment]
@KATT I was just about to change the `IsRecord` type to be a bit more restrictive... I'm sure having it like that will again break something 😂 😂
