### PR TITLE
fix(server): parse url safer in fetch adapter

### LINKED ISSUE #5405: bug:
### Provide environment information

```
  System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 AMD Ryzen 5 5600X 6-Core Processor
    Memory: 12.13 GB / 31.93 GB
  Binaries:
    Node: 20.10.0 - D:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.2.3 - D:\Program Files\nodejs\npm.CMD
    pnpm: 8.14.3 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    Edge: Chromium (120.0.2210.133)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    typescript: ^5.3.3 => 5.3.3
```

### Describe the bug

If I call the tRPC fetch api I get this error:
```
⨯ TypeError: Invalid URL
at new URL (node:internal/url:775:36)
at fetchRequestHandler (file:///F:/programming-projects/Weather-App/node_modules/.pnpm/@trpc+server@10.45.0/node_modules/@trpc/server/dist/adapters/fetch/index.mjs:24:17)
at handler (webpack-internal:///(api)/./src/pages/api/trpc/[trpc].ts:16:92)
at F:\programming-projects\Weather-App\node_modules\.pnpm\next@14.1.0_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\pages-api.runtime.dev.js:21:3039
at F:\programming-projects\Weather-App\node_modules\.pnpm\next@14.1.0_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\lib\trace\tracer.js:133:36
at NoopContextManager.with (F:\programming-projects\Weather-App\node_modules\.pnpm\next@14.1.0_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\@opentelemetry\api\index.js:1:7062)
at ContextAPI.with (F:\programming-projects\Weather-App\node_modules\.pnpm\next@14.1.0_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\@opentelemetry\api\index.js:1:518)
at NoopTracer.startActiveSpan (F:\programming-projects\Weather-App\node_modules\.pnpm\next@14.1.0_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\@opentelemetry\api\index.js:1:18093)
at ProxyTracer.startActiveSpan (F:\programming-projects\Weather-App\node_modules\.pnpm\next@14.1.0_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\@opentelemetry\api\index.js:1:18854)
at F:\programming-projects\Weather-App\node_modules\.pnpm\next@14.1.0_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\lib\trace\tracer.js:122:103
at NoopContextManager.with (F:\programming-projects\Weather-App\node_modules\.pnpm\next@14.1.0_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\@opentelemetry\api\index.js:1:7062)
at ContextAPI.with (F:\programming-projects\Weather-App\node_modules\.pnpm\next@14.1.0_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\@opentelemetry\api\index.js:1:518)
at NextTracerImpl.trace (F:\programming-projects\Weather-App\node_modules\.pnpm\next@14.1.0_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\lib\trace\tracer.js:122:28)
at K (F:\programming-projects\Weather-App\node_modules\.pnpm\next@14.1.0_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\pages-api.runtime.dev.js:21:2970)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
code: 'ERR_INVALID_URL',
input: '/api/trpc/weather.getWeather?batch=1&input=%7B%220%22%3A%7B%22json%22%3A%7B%22coordinates%22%3A%7B%22lat%22%3A52.30141%2C%22lon%22%3A13.633%7D%2C%22timezone%22%3A%22Europe%2FBerlin%22%2C%22lang%22%3A%22en%22%7D%7D%7D',
page: '/api/trpc/[trpc]'
}
```

### Link to reproduction

https://codesandbox.io/p/sandbox/github/The-Creative-Programming-Group/Weather-App/tree/move-to-edge

### To reproduce

Fill out all the envs according to the env.example file
Start the dev server in the codesandbox and go to /home
look in the terminal and see the error

### Additional information

If there is enough information I could try to fix this bug.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

### PR DESCRIPTION
**Pull request by KATT**
Might close #5405

## 🎯 Changes

Parse url in a safer way

### CODE REVIEW

File: packages/server/src/adapters/standalone.ts [hunk 1]
```diff
@@ -19,18 +20,15 @@ export function createHTTPHandler<TRouter extends AnyRouter>(
...
 
     // get procedure path and remove the leading slash
     // /procedure -> procedure
-    const path = new URL(href).pathname.slice(1);
+    const path = url.pathname.slice(1);
 
     await nodeHTTPRequestHandler({
       // FIXME: no typecasting should be needed here
-      ...(opts as CreateHTTPHandlerOptions<AnyRouter>),
+      ...opts,
```
Comment (KATT) [inline packages/server/src/adapters/standalone.ts:31]:
```suggestion
      ...(opts as CreateHTTPHandlerOptions<AnyRouter>),
```
