### PR TITLE
fix(next): reusing same instance of ssg helpers across pages

### LINKED ISSUE #6558: bug: Serialization issues on dependant queries (NextJS)
### Provide environment information

```
System:
    OS: macOS 15.3.1
    CPU: (8) arm64 Apple M1
    Memory: 2.35 GB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.14.0 - ~/.nvm/versions/node/v22.14.0/bin/node
    npm: 10.9.2 - ~/.nvm/versions/node/v22.14.0/bin/npm
    pnpm: 10.4.1 - ~/.nvm/versions/node/v22.14.0/bin/pnpm
    Watchman: 2021.09.27.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 133.0.6943.127
    Safari: 18.3
  npmPackages:
    @tanstack/react-query: 5.66.0 => 5.66.0 
    @trpc/client: 11.0.0-rc.804 => 11.0.0-rc.804+ab12d16b0 
    @trpc/next: 11.0.0-rc.804 => 11.0.0-rc.804+ab12d16b0 
    @trpc/react-query: 11.0.0-rc.804 => 11.0.0-rc.804+ab12d16b0 
    @trpc/server: 11.0.0-rc.804 => 11.0.0-rc.804+ab12d16b0 
    next: 15.1.7 => 15.1.7 
    react: 19.0.0 => 19.0.0 
    typescript: 5.7.3 => 5.7.3 
```

### Describe the bug

Doing a migration from v10 to v11 in T3 based app. **It worth to mention that the same code works with no issues on v10.**
Full description: https://discord.com/channels/867764511159091230/1336292204045668352
TL;DR
I faced a weird issue:"Error serializing `.trpcState.json.queries[26].promise` returned from `getStaticProps`" using fetch + prefetch in getStaticProps.
I noticed that that happens only in case of dependant queries. helper.dyhydrate() returns promise like data mixed with real responses. That data is not serialized so NextJS throw en error.
Wrapping **helper.dyhydrate()** into JSON.stringify make builds pass, but I guess that just a way to mute errors and hide underlying problems.
Another way - refactor code from dependant queries to just one but that's not seem to be right way to do things.
In general I have no urgent need for a temporary solution, and I can wait for a fix in version 11 using version 10 which doesn't have this problem.

### Link to reproduction

https://github.com/MadaShindeInai/trpcreactqueryissuerepro/tree/main

### To reproduce

`git clone git@github.com:MadaShindeInai/trpcreactqueryissuerepro.git`
`cd trpcreactqueryissuerepro`
`pnpm i`
`pnpm build`

### Additional information

Discord question: https://discord.com/channels/867764511159091230/1020132255567454310/threads/1336292204045668352
Twitter question:
https://x.com/MadaShindeInai/status/1893626390664114340

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

### PR DESCRIPTION
**Pull request by KATT**
Closes #6558

## 🎯 Changes

> The problem seems to be that you're creating the SSG helpers outside of the `getStaticProps()` so they will reshare the same `QueryClient` which means it will contain a pending `promise` which cannot be hydrated.
> 
> `promise` wasn't a property in TanStack Query v4
> 
> I will make it be omitted 

 _Originally posted by @KATT in [#6558](https://github.com/trpc/trpc/issues/6558#issuecomment-2690625804)_

## Summary by CodeRabbit

- **New Features**
  - Enhanced server-side data handling to ensure that only complete data is processed during static page generation, resulting in more reliable content display.

- **Tests**
  - Expanded testing to verify that server-rendered pages consistently receive fully processed data, even when reusing the same rendering instance.

### CODE REVIEW

File: packages/react-query/src/server/ssgProxy.ts [hunk 1]
```diff
@@ -120,13 +121,29 @@ export function createServerSideHelpers<TRouter extends AnyRouter>(
 
   function _dehydrate(
     opts: DehydrateOptions = {
-      shouldDehydrateQuery() {
+      shouldDehydrateQuery(query) {
+        if (query.state.status === 'pending') {
+          return false;
+        }
```
Comment (juliusmarminge) [inline packages/react-query/src/server/ssgProxy.ts:127]: FYI: this is already default behavior

Comment (juliusmarminge) [reply packages/react-query/src/server/ssgProxy.ts:127]: oh nvm we're falling back to true for everything below...
