### PR TITLE
fix(fastify adapter): prevent duplicate content type parsers

### LINKED ISSUE #4820: bug: [fastify adapter] error in nestjs/fastify-adapter FastifyError: Content type parser 'application/json' already present.
### Provide environment information

```
 System:
    OS: macOS 14.0
    CPU: (12) arm64 Apple M2 Max
    Memory: 933.14 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.1 - ~/.n/bin/node
    npm: 8.19.4 - ~/.n/bin/npm
    pnpm: 8.7.4 - ~/.n/bin/pnpm
    Watchman: 2023.09.18.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 116.0.5845.187
    Chrome Canary: 119.0.6020.2
    Safari: 17.0
  npmPackages:
    @trpc/server: 10.38.4 => 10.38.4 
```

server side only

### Describe the bug

```ts
 applyMiddleware(app: NestFastifyApplication) {
    app.register(fastifyTRPCPlugin, {
      prefix: '/trpc',
      trpcOptions: { router: this.appRouter, createContext },
    })
  }
```

And I apply fastify plugin, and throw an error.

```


 ERROR  FastifyError: Content type parser 'application/json' already present.                                                                                                        23:38:11
    at ContentTypeParser.add (/Users/innei/git/innei-repo/MetaMuse/node_modules/.pnpm/fastify@4.22.2/node_modules/fastify/lib/contentTypeParser.js:50:11)
    at Object.addContentTypeParser (/Users/innei/git/innei-repo/MetaMuse/node_modules/.pnpm/fastify@4.22.2/node_modules/fastify/lib/contentTypeParser.js:337:30)
    at fastifyTRPCPlugin (/Users/innei/git/innei-repo/MetaMuse/node_modules/.pnpm/@trpc+server@10.38.4/node_modules/@trpc/server/dist/adapters/fastify/index.js:91:13)
    at Plugin.exec (/Users/innei/git/innei-repo/MetaMuse/node_modules/.pnpm/avvio@8.2.1/node_modules/avvio/plugin.js:130:19)
    at Boot.loadPlugin (/Users/innei/git/innei-repo/MetaMuse/node_modules/.pnpm/avvio@8.2.1/node_modules/avvio/plugin.js:272:10)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
```

### Link to reproduction

https://github.com/Innei/trpc-fastify-repro

### To reproduce

This bug is similar https://github.com/nestjs/nest/issues/5607

```
pnpm i
pnpm run dev

```

### Additional information

_No response_

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/4820">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/4820/pledge.svg?darkmode=1">
  Fund with Polar
</picture>
</a>

### PR DESCRIPTION
**Pull request by KATT**
Closes #4820

> I don't know Fastify well enough to understand why #4854 changes the behavior. Help @skarab42 or @Innei 🙏 
> 
> ```shell
> gh pr checkout 4854
> pnpm i
> pnpm build
> pnpm vitest fastify
> ```
> 
> _Originally posted by @KATT in https://github.com/trpc/trpc/issues/4820#issuecomment-1738304638_

### CODE REVIEW

File: packages/server/src/adapters/fastify/fastifyTRPCPlugin.ts [hunk 1]
```diff
@@ -22,13 +22,15 @@ export function fastifyTRPCPlugin<TRouter extends AnyRouter>(
...
-  );
+  if (!fastify.hasContentTypeParser('application/json')) {
+    fastify.addContentTypeParser(
+      'application/json',
+      { parseAs: 'string' },
+      function (_, body, _done) {
+        _done(null, body);
+      },
+    );
+  }
```
Comment (skarab42) [inline packages/server/src/adapters/fastify/fastifyTRPCPlugin.ts:33]: I'm not sure why this happens (I don't have much time to go into it), but my theory is that the content parser is explicitly defined by another plugin before the trpc adapter is initialized, and fastifiy doesn't allow you to change it even though you're in the scope of the trpc adapter. The fix I've found is to unregister it before adding it again for this scope.

```suggestion
  fastify.removeContentTypeParser('application/json');
  fastify.addContentTypeParser(
    'application/json',
    { parseAs: 'string' },
    function (_, body, _done) {
      _done(null, body);
    },
  );
```

Comment (skarab42) [reply packages/server/src/adapters/fastify/fastifyTRPCPlugin.ts:33]: Probably related to https://github.com/nestjs/nest/commit/0444f9c89e61b5924cb4f9532303b9bb1d994787#diff-7601c6884e46e07a23aae0fea72039261b51395017f5ef74f58bb7a2519e5cb1R479 add 9 months ago

Comment (skarab42) [reply packages/server/src/adapters/fastify/fastifyTRPCPlugin.ts:33]: I think this happens when nestjs puts the body parser on the Fastify root instance rather than on their adapter instance : https://github.com/nestjs/nest/commit/0444f9c89e61b5924cb4f9532303b9bb1d994787#diff-7601c6884e46e07a23aae0fea72039261b51395017f5ef74f58bb7a2519e5cb1R208

Comment (Innei) [reply packages/server/src/adapters/fastify/fastifyTRPCPlugin.ts:33]: https://github.com/nestjs/nest/blob/master/packages/platform-fastify/adapters/fastify-adapter.ts#L596

🤔
