### PR TITLE
fix: export DataTransformer interface marked as @public

### LINKED ISSUE #6916: bug: DataTransformer type is not exported
### Provide environment information

```
  System:
    OS: macOS 15.6
    CPU: (12) arm64 Apple M3 Pro
    Memory: 124.16 MB / 18.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 24.5.0 - ~/.local/share/mise/installs/node/24.5.0/bin/node
    npm: 11.5.1 - ~/.local/share/mise/installs/node/24.5.0/bin/npm
    pnpm: 10.14.0 - ~/.local/share/mise/installs/node/24.5.0/bin/pnpm
  Browsers:
    Chrome: 139.0.7258.154
    Safari: 18.6
  npmPackages:
    @trpc/client: ^11.4.4 => 11.4.4 
    @trpc/server: ^11.4.4 => 11.4.4 
    typescript: ^5.9.2 => 5.9.2 
```

### Describe the bug

The `DataTransformer` type is declared as public:

https://github.com/trpc/trpc/blob/e6fc3098524eb248b77fbbd5b4f7806070c21d40/packages/server/src/unstable-core-do-not-import/transformer.ts#L10-L16

However, it's not exported by neither `@trpc/server` nor `@trpc/client`. I believe it should be exported by both.

### Link to reproduction

https://stackblitz.com/edit/github-1imszvlx?file=src%2Futils%2Ftransformer.ts

### To reproduce

Just open the reproduction and see import error.

### Additional information

My use case is that I want a single transformer object for both the client- and server-side (which I believe most people need), but there is no way to type it properly. Currently, I have to use `CombinedDataTransformer["input"]` which is a hack and it misleads developers (because `input` is advertised to be client -> server transformer).

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

### PR DESCRIPTION
**Pull request by BhaskarKulshrestha**
# Pull Request Summary: Export DataTransformer Interface #6916 

Closes #6926
Closes #6916 

## Description
This PR resolves an issue where the `DataTransformer` interface was marked as `@public` but not exported from either `@trpc/server` or `@trpc/client` packages, preventing users from properly typing their custom transformers.

## Issue Fixed
- **Problem**: Users couldn't import `DataTransformer` interface despite it being marked as public API
- **Workaround**: Users had to use confusing `CombinedDataTransformer["input"]` hack
- **Root Cause**: Missing exports in package entry points
- 
### Server Package (`@trpc/server`)
- Added `DataTransformer` export to main index
- Added `TRPCDataTransformer` alias following naming conventions
- Added backward compatibility deprecation notice

### Client Package (`@trpc/client`) 
- Added convenient re-export of `DataTransformer` from server package
- Maintains single source of truth

## Testing
- [x] All packages build successfully
- [x] Type exports verified in built packages
- [x] Existing transformer tests pass
- [x] No breaking changes introduced
- [x] Backward compatibility maintained
### Before
```typescript
import type { DataTransformer } from '@trpc/server';
type MyTransformer = CombinedDataTransformer["input"];
```
### After
```typescript
import type { DataTransformer } from '@trpc/server';
import type { DataTransformer } from '@trpc/client';
const myTransformer: DataTransformer = {
  serialize: (obj) => obj,
  deserialize: (obj) => obj,
};
```
## Safety
- **Breaking Changes**: None
- **Runtime Impact**: None (types only)
- **Backward Compatibility**: Full
- **Code Style**: Follows project conventions
## Contribution Guidelines Compliance
- [x] Used pnpm for package management
- [x] Ran `pnpm build` successfully
- [x] Ran `pnpm lint-fix`
- [x] Added proper documentation
- [x] Followed existing code patterns
- [x] Maintained type safety
- [x] No cryptic errors introduced

## Summary by CodeRabbit

* New Features
  * Introduced TRPCDataTransformer type alias for clearer naming in server exports.
  * Client package now publicly re-exports the DataTransformer type for convenience.

* Documentation
  * Deprecated DataTransformer in favor of TRPCDataTransformer across public exports.
  * Clarified that these are type-only changes with no impact on runtime behavior.

### CODE REVIEW

File: packages/client/src/index.ts [hunk 1]
```diff
@@ -18,3 +18,6 @@ export {
 } from './createTRPCClient';
 
 export { type TRPCProcedureOptions } from './internals/types';
+
+// Export DataTransformer from server package for convenience
+export type { DataTransformer } from '@trpc/server';
```
Comment (KATT) [inline packages/client/src/index.ts]: I prefer just exporting it from one place

```suggestion
````

**Review by KATT — APPROVED** [review]
