### PR TITLE
fix(sse): combine abort signal with internal one

### LINKED ISSUE #6126: bug: dangling async generator on internal cancel within `sseStreamProducer`
### Provide environment information

n/a

### Describe the bug

As discussed with @KATT :

sse.ts `sseStreamProducer(...)` has some cancel conditions on which to abort further handling (namely, `opts.emitAndEndImmediately` & `opts.maxDurationMs`).
When those trigger, the emit of further data is stopped, but the userland abort signal is not coupled with this. So, any potential userland event listener does not stop immediately, but only after the next `yield` (as we at least call `iterator.return()`).

### Link to reproduction

n/a

### To reproduce

n/a

### Additional information

_No response_

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/6126">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/6126/pledge.svg?darkmode=1">
  Fund with Polar
</picture>
</a>

### PR DESCRIPTION
**Pull request by oleasteo**
Closes #6126

## 🎯 Changes

Added `AbortController` to internal `subscription` processing to avoid dangling generators in userland.

Consider userland like this:

```ts 
procedure.subscription(async function* (opts) {
    // listen for new events
    for await (const [data] of on(ee, 'add', { signal: opts.signal })) {
      const post = data as Post;
      yield post;
    }
  })
```

Before the changes, this would have had a dangling event listener (for just the very next event) **after** `opts.emitAndEndImmediately` or `opts.maxDurationMs` triggered. With the changes, the `opts.signal` triggers with these cancel conditions, so the event listener will be cleaned up properly.

## ✅ Checklist

- [x] I have followed the steps listed in the [Contributing guide](https://github.com/trpc/trpc/blob/main/CONTRIBUTING.md).
- [x] If necessary, I have added documentation related to the changes made.
- [x] I have added or updated the tests related to the changes made.

### CODE REVIEW

**Review by Thompson1985 — APPROVED** [review]

File: packages/server/src/unstable-core-do-not-import/utils.ts [hunk 1]
```diff
@@ -68,3 +68,51 @@ export function noop(): void {}
...
+  }
+
+  const ac = new AbortController();
+
+  for (const signal of signals) {
+    if (signal.aborted) {
+      trigger();
+    } else if (!ac.signal.aborted) {
+      signal.addEventListener('abort', trigger, { once: true });
+    }
```
Comment (KATT) [inline packages/server/src/unstable-core-do-not-import/utils.ts:107]: Simplified

```suggestion
    if (signal.aborted) {
      trigger();
      break;
    }
    signal.addEventListener('abort', trigger, { once: true });
```

File: packages/server/src/unstable-core-do-not-import/stream/utils/asyncIterable.ts [hunk 2]
```diff
@@ -27,6 +27,7 @@ export async function* withCancel<T>(
 interface TakeWithGraceOptions {
   count: number;
   gracePeriodMs: number;
+  onCancel?: () => void;
```
Comment (KATT) [inline packages/server/src/unstable-core-do-not-import/stream/utils/asyncIterable.ts:30]: Can't this be an abort signal instead of a callback?

Also, I think it's only used in one place, no need to make it optional

**Review by KATT — APPROVED** [review]

File: packages/server/src/unstable-core-do-not-import/stream/utils/asyncIterable.ts (hunk 2 above)
Comment (oleasteo) [reply packages/server/src/unstable-core-do-not-import/stream/utils/asyncIterable.ts:30]: It could be an abort ctrl passed in. But I like to not make util functions too specific. If there's a simpler or more generic way, without adding pretty much any effort, it's best to keep util functions generic or simple. In this case, I'd argue it's both more simple and generic. Lean function headers are great.

File: packages/server/src/unstable-core-do-not-import/utils.ts (hunk 1 above)
Comment (oleasteo) [reply packages/server/src/unstable-core-do-not-import/utils.ts:107]: oops. I misinterpreted the github mobile view and thought this was already edited into the PR :see_no_evil:
