### PR TITLE
fix(server): middleware input requirements shouldn't widen procedure inputs

### LINKED ISSUE #5056: A narrower input type earlier in the procedure chain should not widen due to a middleware's wider input requirements
### Provide environment information

...

### Describe the bug

As far as I am concerned, all relevant background is in this discussion: https://github.com/trpc/trpc/discussions/5051

### Link to reproduction

https://github.com/trpc/trpc/discussions/5051

### To reproduce

Copy paste the code from https://github.com/trpc/trpc/discussions/5051

### Additional information

I already have a fix for this

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5056">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5056/pledge.svg?darkmode=1">
  Fund with Polar
</picture>
</a>

### PR DESCRIPTION
**Pull request by jussisaurio**
…rocedure inputs

Closes #5056

## 🎯 Changes

E.g.

```
.input(z.object({ foo: string })
.use(middlewareThatRequiresOptionalFoo)
.query(({ input }) => ...)
```

input.foo should still be string, not an optional string.

## ✅ Checklist

- [x] I have followed the steps listed in the [Contributing guide](https://github.com/trpc/trpc/blob/main/CONTRIBUTING.md).
- [ ] If necessary, I have added documentation related to the changes made.
- [x] I have added or updated the tests related to the changes made.

### CODE REVIEW

File: packages/server/src/core/internals/utils.ts [hunk 1]
```diff
@@ -21,7 +21,8 @@ export type Overwrite<TType, TWith> = TWith extends any
         ? { [key: string]: TWith[string] }
         : number extends keyof TWith
         ? { [key: number]: TWith[number] }
-        : object)
+        : // eslint-disable-next-line @typescript-eslint/ban-types
+          {})
```
Comment (jussisaurio) [inline packages/server/src/core/internals/utils.ts:25]: tbh this is unrelated to this pr, I just realized that `object` intersection uglifies types, whereas `{}` does not.

**Review by KATT — APPROVED** [review]
