### PR TITLE
fix(server): handle large POST bodies in node-http

### LINKED ISSUE #5725: bug: trpc/server node-http adapter fails to read large POST body
### Provide environment information

```
  System:
    OS: Linux 6.1 Manjaro Linux
    CPU: (24) x64 13th Gen Intel(R) Core(TM) i7-13700
    Memory: 25.82 GB / 62.54 GB
    Container: Yes
    Shell: 5.2.26 - /bin/bash
  Binaries:
    Node: 20.12.1 - ~/.nvm/versions/node/v20.12.1/bin/node
    npm: 10.5.0 - ~/.nvm/versions/node/v20.12.1/bin/npm
    pnpm: 8.15.5 - ~/.nvm/versions/node/v20.12.1/bin/pnpm
    bun: 1.1.8 - /usr/bin/bun
  npmPackages:
    typescript: ^5.4.5 => 5.4.5
```

### Describe the bug

I'm using trpc to POST large JSON objects to my backend. I've noticed that large bodies are truncated since the rewrite in #5684. In my case, this results in an error of:

```
[
  {
    "error": {
      "message": "Unterminated string in JSON at position 16375",
      "code": -32600,
      "data": {
        "code": "BAD_REQUEST",
        "httpStatus": 400,
        "stack": "TRPCError: Unterminated string in JSON at position 16375\n    at file:///app/node_modules/@trpc/server/dist/unstable-core-do-not-import/http/contentType.mjs:23:27\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Object.read (file:///app/node_modules/@trpc/server/dist/unstable-core-do-not-import/http/contentType.mjs:30:21)\n    at async Object.getRawInput (file:///app/node_modules/@trpc/server/dist/unstable-core-do-not-import/http/contentType.mjs:89:40)\n    at async inputValidatorMiddleware (file:///app/node_modules/@trpc/server/dist/unstable-core-do-not-import/middleware.mjs:42:26)\n    at async callRecursive (file:///app/node_modules/@trpc/server/dist/unstable-core-do-not-import/procedureBuilder.mjs:152:32)\n    at async procedure (file:///app/node_modules/@trpc/server/dist/unstable-core-do-not-import/procedureBuilder.mjs:182:24)\n    at async file:///app/node_modules/@trpc/server/dist/unstable-core-do-not-import/http/resolveResponse.mjs:135:30\n    at async Promise.all (index 0)\n    at async resolveResponse (file:///app/node_modules/@trpc/server/dist/unstable-core-do-not-import/http/resolveResponse.mjs:178:37)\n    at async file:///app/node_modules/@trpc/server/dist/adapters/node-http/nodeHTTPRequestHandler.mjs:33:26\n    at async file:///app/node_modules/@trpc/server/dist/adapters/express.mjs:7:9",
        "path": "trpcMethodName"
      }
    }
  }
]
```

In doing some testing, I believe that the issue with the current trpc server code is that the `incomingMessageToBodyStream` function is not properly reading the full stream.

https://github.com/trpc/trpc/blob/3dc8f3be2d5848a3c7b54da357c74b0db146b32d/packages/server/src/adapters/node-http/incomingMessageToRequest.ts#L23-L50

The issue occurs when the `pull` method is called before there is anything new to read, but the body has not been fully parsed. This seems to happen either when a highwater mark is reached on an internal stream or there is a break in the delivery of the network packets. 

When the `pull` method is called, but `read()` returns `null`, the `controller.enqueue` function is not called, which causes the ReadableStream to stop calling `pull`. This wasn't obvious to me either, but is clearly stated on the [MDN page](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream/ReadableStream#pull):

> pull (optional)
> This method, also defined by the developer, will be called repeatedly when the stream's internal queue of chunks is not full, up until it reaches its high water mark. If pull() returns a promise, then it won't be called again until that promise fulfills; if the promise rejects, the stream will become errored. The controller parameter passed to this method is a [ReadableStreamDefaultController](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStreamDefaultController) or a [ReadableByteStreamController](https://developer.mozilla.org/en-US/docs/Web/API/ReadableByteStreamController), depending on the value of the type property. This can be used by the developer to control the stream as more chunks are fetched. This function will not be called until start() successfully completes. Additionally, **it will only be called repeatedly if it enqueues at least one chunk** or fulfills a BYOB request; a no-op pull() implementation will not be continually called.

(bolded text is mine)

### Link to reproduction

https://github.com/trpc/trpc/pull/5724

### To reproduce

Checkout the PR (https://github.com/trpc/trpc/pull/5724) and confirm that the new test fails without the accompanying bugfix, but all tests pass with the fix.

### Additional information

_No response_

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5725">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5725/pledge.svg?darkmode=1">
  Fund with Polar
</picture>
</a>

### PR DESCRIPTION
**Pull request by jcarrus**
Closes #5725

## 🎯 Changes

Fixes a bug where node-http server would truncate POST bodies.

## ✅ Checklist

- [x] I have followed the steps listed in the [Contributing guide](https://github.com/trpc/trpc/blob/main/CONTRIBUTING.md).
- [x] If necessary, I have added documentation related to the changes made.
- [x] I have added or updated the tests related to the changes made.

### CODE REVIEW

File: packages/server/src/adapters/node-http/incomingMessageToRequest.ts [hunk 1]
```diff
@@ -17,32 +17,32 @@ function incomingMessageToBodyStream(
...
+            }),
+          );
+          // an error is thrown if we try to close the controller after
+          // erroring, so track the closure
+          hasClosed = true;
+          return;
+        }
+        controller.enqueue(chunk);
+      });
+      req.on('end', () => {
```
Comment (KATT) [inline packages/server/src/adapters/node-http/incomingMessageToRequest.ts:39]: it doesn't really matter but this is tidier
```suggestion
      req.once('end', () => {
```

**Review by KATT — COMMENTED** [review]
Thank you so much for this!

**Review by KATT — APPROVED** [review]
